# Generated by Django 4.2.3 on 2023-10-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=125, verbose_name='Наименование')),
                ('serial', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Серийный номер кассы')),
                ('enabled', models.BooleanField(default=False, verbose_name='Запуск эмулятора разрешён')),
                ('port', models.IntegerField(unique=True, verbose_name='Порт на котором работает api эмулятора')),
                ('path', models.CharField(max_length=1024, verbose_name='Полный путь к профилю')),
                ('note', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Примечание')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('pid', models.IntegerField()),
                ('id_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.profile')),
            ],
        ),
    ]
